name: Test

on:
  workflow_call:
    inputs:
      dolfinx_tag:
        required: true
        type: string

jobs:
  test-code:
    runs-on: ubuntu-24.04
    # The container tag is now dynamic based on the input passed by the caller
    container: ghcr.io/fenics/dolfinx/dolfinx:${{ inputs.dolfinx_tag }}

    steps:
      - uses: actions/checkout@v6

      - name: Update pip
        run: python3 -m pip install --upgrade pip

      - name: Install build requirements
        run: python3 -m pip install -r build-requirements.txt

      # Note: We assume the caller workflow has already uploaded these artifacts
      - name: Download legacy data
        uses: actions/download-artifact@v7
        with:
          name: legacy_mpich
          path: ./legacy

      - name: Download legacy data
        uses: actions/download-artifact@v7
        with:
          name: legacy_checkpoint_mpich
          path: ./legacy_checkpoint

      - name: Install package
        run: |
          HDF5_MPI=ON HDF5_PKGCONFIG_NAME="hdf5" python3 -m pip install h5py --no-build-isolation --no-binary=h5py
          python3 -m pip install .[test]

      - name: Run tests
        run: coverage run --rcfile=.coveragerc -m pytest -xvs ./tests/

      - name: Run tests in parallel
        run: mpirun -n 4 coverage run --rcfile=.coveragerc -m mpi4py -m pytest -xvs ./tests/

      - name: Combine coverage reports
        run: |
          coverage combine
          coverage report -m
          coverage html

      # Use the tag in the artifact name so parallel runs don't overwrite each other
      - name: Upload coverage report
        uses: actions/upload-artifact@v6
        with:
          name: code-coverage-report-${{ inputs.dolfinx_tag }}
          path: htmlcov
          if-no-files-found: error